//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKBBoard.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        public int id { get; set; }
        public string deptName { get; set; }
        public string deptShortcode { get; set; }
        public string deptEmail { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public string createdBy { get; set; }
    }
}
