//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKBBoard.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class loginUser
    {
        public int id { get; set; }
        public string userID { get; set; }
        public string password { get; set; }
        public string userName { get; set; }
        public string userRole { get; set; }
        public string userDept { get; set; }
        public string isActive { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public string updatedBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
    }
}
