//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKBBoard.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingDetail
    {
        public int ID { get; set; }
        public int MeetingID { get; set; }
        public int MemoSerial { get; set; }
        public string Subject { get; set; }
        public int Dept { get; set; }
        public string memoURL { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UserMemoFileName { get; set; }
        public string MemoSubSerial { get; set; }
    }
}
