//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKBBoard.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingMaster
    {
        public int ID { get; set; }
        public int MeetingNo { get; set; }
        public int MeetingType { get; set; }
        public string Title { get; set; }
        public System.DateTime Date { get; set; }
        public string AgendaURL { get; set; }
        public string MinutesURL { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UserFileName { get; set; }
        public string UserMinuteFileName { get; set; }
    }
}
